import os
import json
import logging
from typing import Literal, TypedDict

from dotenv import load_dotenv
from pydantic import BaseModel, Field
from pinecone.grpc import PineconeGRPC as Pinecone

from langchain.chat_models import init_chat_model
from langchain.messages import HumanMessage, SystemMessage
from langgraph.graph import StateGraph, START, END
from langchain_core.runnables import RunnableConfig

from erp_info import ERPClient, ERPError, ERPData


# ============================================================
# Configuration
# ============================================================

load_dotenv()

GROQ_API_KEY = os.getenv("GROQ_API_KEY")
PC_API_KEY = os.getenv("PC_API_KEY")

COLLEGE_NAMESPACE = os.getenv("COLLEGE_NAMESPACE", "doc1")
CURRENT_INFO_NAMESPACE = os.getenv(
    "CURRENT_INFO_NAMESPACE",
    "fit-markdown-data",
)
CLASSIFIER_MODEL = os.getenv("CLASSIFIER_MODEL", "openai/gpt-oss-120b")
CHAT_MODEL = os.getenv("CHAT_MODEL", "openai/gpt-oss-120b")
COLLEGE_TOP_K = int(os.getenv("COLLEGE_TOP_K", "2"))
CURRENT_INFO_TOP_K = int(os.getenv("CURRENT_INFO_TOP_K", "3"))

if not GROQ_API_KEY:
    raise RuntimeError("GROQ_API_KEY is not configured.")

if not PC_API_KEY:
    raise RuntimeError("PC_API_KEY is not configured.")

pc = Pinecone(api_key=PC_API_KEY)
index = pc.Index("akgec-data")

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
)

logger = logging.getLogger(__name__)


# ============================================================
# Structured classifier output
# ============================================================

class RetrievalRequest(BaseModel):
    """One retrieval operation from the classifier."""

    source: Literal[
        "student_erp",
        "college_database",
        "current_info",
    ] = Field(
        description=(
            "Retrieval source: student_erp for private student ERP data, "
            "college_database for stable/public AKGEC information, and "
            "current_info for current or time-sensitive AKGEC information."
        )
    )

    search_query: str | None = Field(
        default=None,
        description=(
            "Focused query for this retrieval. Required for "
            "college_database and current_info, and should describe the "
            "requested information for student_erp."
        ),
    )

    student_id: str | None = Field(
        default=None,
        description=(
            "Student ID / roll number copied exactly from the CURRENT user "
            "message. Required only for student_erp. Never infer or fabricate."
        ),
    )

    password: str | None = Field(
        default=None,
        description=(
            "ERP password copied exactly from the CURRENT user message. "
            "Required only for student_erp. Never infer or fabricate."
        ),
    )


class ClassifierOutput(BaseModel):
    """Simple retrieval plan generated by the classifier."""

    decision: Literal[
        "retrieval_required",
        "retrieval_not_required",
        "access_denied",
    ] = Field(
        description=(
            "retrieval_not_required when no retrieval is needed; "
            "retrieval_required when one or more retrievals should run; "
            "access_denied when the only requested retrieval is private ERP "
            "data but required credentials are missing."
        )
    )

    retrievals: list[RetrievalRequest] = Field(
        default_factory=list,
        description=(
            "One or more retrieval requests. A single user query may use "
            "multiple retrieval sources."
        ),
    )

    denied_reason: str | None = Field(
        default=None,
        description=(
            "Optional explanation when a private ERP part cannot be "
            "retrieved because required credentials are missing."
        ),
    )


# ============================================================
# LangGraph state
# ============================================================

class State(TypedDict, total=False):
    input: str
    history: str
    plan: ClassifierOutput
    retrieval_results: list[dict]
    context: str
    output: str


# ============================================================
# Retrieval functions
# ============================================================

def student_data(student_id: str, password: str) -> ERPData | None:
    """Fetch private student ERP data."""

    try:
        with ERPClient(student_id, password) as client:
            return client.fetch_data()

    except ERPError as exc:
        logger.error("ERP error: %s", exc)
        return None


def pinecone_search(query: str, namespace: str, top_k: int) -> dict:
    """Run Pinecone similarity search and return text context."""

    try:
        query_embedding = pc.inference.embed(
            model="llama-text-embed-v2",
            inputs=[query],
            parameters={"input_type": "query"},
        )

        results = index.query(
            namespace=namespace,
            vector=query_embedding[0].values,
            top_k=top_k,
            include_values=False,
            include_metadata=True,
        )

        chunks = []

        for match in results.get("matches", []):
            source_text = match.get("metadata", {}).get("source_text")

            if source_text:
                chunks.append(str(source_text))

        context = " ".join(chunks).strip()

        return {
            "context": context,
            "approx_token": len(context) / 4 if context else 0,
        }

    except Exception as exc:
        logger.exception(
            "Pinecone retrieval failed. namespace=%s error=%s",
            namespace,
            exc,
        )

        return {
            "context": "",
            "approx_token": 0,
        }


def college_database_search(query: str) -> dict:
    """Retrieve stable/public AKGEC information."""

    return pinecone_search(
        query=query,
        namespace=COLLEGE_NAMESPACE,
        top_k=COLLEGE_TOP_K,
    )


def current_info_search(query: str) -> dict:
    """Retrieve current/time-sensitive AKGEC information."""

    return pinecone_search(
        query=query,
        namespace=CURRENT_INFO_NAMESPACE,
        top_k=CURRENT_INFO_TOP_K,
    )


# ============================================================
# Models
# ============================================================

classifier_model = init_chat_model(
    CLASSIFIER_MODEL,
    model_provider="groq",
    api_key=GROQ_API_KEY,
    max_tokens=2048,
    timeout=600,
    temperature=0,
    streaming=False,
    max_retries=1,
)

answer_model = init_chat_model(
    CHAT_MODEL,
    model_provider="groq",
    api_key=GROQ_API_KEY,
    max_tokens=2048,
    timeout=600,
    temperature=0.5,
    streaming=True,
    max_retries=1,
)

classifier_model_structured = classifier_model.with_structured_output(
    ClassifierOutput
)


# ============================================================
# Prompts
# ============================================================

ROUTER_PROMPT = """You are the retrieval classifier for an AKGEC campus chatbot.

Use the ClassifierOutput schema.

AVAILABLE SOURCES:

1. student_erp
   Use only for private student-specific ERP data such as attendance,
   marks, academic records, fees, personal timetable, etc.

   Requirements:
   - BOTH student_id and password MUST appear in the CURRENT user message or in the conversation history / state.
   - Copy them exactly.
   - Never infer, guess, remember, or fabricate credentials.
   - search_query should describe the specific student information requested.

2. college_database
   Use for stable/public AKGEC information such as faculty, people,
   departments, courses, admissions, placements, campus, facilities,
   rules, and other college knowledge-base information.

   Only search_query is required.

3. current_info
   Use for current/time-sensitive AKGEC information such as current
   events, today's notices, recent announcements, current schedules,
   and similar changing information.

   Only search_query is required.

ROUTING RULES:

1. One user query MAY require multiple retrievals.
2. Create one item in retrievals for EACH required source/query.
3. Split compound questions into focused retrieval queries.
4. If no retrieval is needed:
   decision = "retrieval_not_required"
   retrievals = []
5. For an ERP request without both credentials:
   do NOT create an executable student_erp retrieval.
6. If a query contains a blocked ERP part and an executable public/current
   part, include the executable retrievals and set denied_reason.
7. Use "access_denied" only when there are no executable retrievals and
   the requested private ERP information is blocked.
8. Never include ERP credentials inside search_query.

Examples:

"What is my attendance? ID=123 password=abc"
-> student_erp

"What is my attendance and who is the CSE HOD? ID=123 password=abc"
-> student_erp + college_database

"Who is the CSE HOD and what events are happening this week?"
-> college_database + current_info

"Hello"
-> retrieval_not_required

"What is my attendance?"
-> access_denied
"""


SYSTEM_PROMPT = """You are a dedicated chatbot for Ajay Kumar Garg Engineering
College (AKGEC).

Answer the user's query using the retrieved context.

Rules:
- Stay relevant to AKGEC.
- If unrelated to AKGEC, politely state that you only assist with
  AKGEC-related questions.
- Do not invent facts absent from the retrieved context.
- For student ERP information, answer only from retrieved ERP data.
- NEVER expose, repeat, or mention the ERP password.
- If a part could not be retrieved because credentials were missing,
  explain that limitation while still answering successfully retrieved parts.
- Use clear formatting with headings, bullets, or tables when useful.
"""


# ============================================================
# Nodes
# ============================================================

def classify_request(state: State) -> dict:
    """Classify the query into zero, one, or multiple retrievals."""

    plan = classifier_model_structured.invoke(
        [
            SystemMessage(content=ROUTER_PROMPT),
            HumanMessage(content=state["input"]),
        ]
    )

    logger.info(
        "decision=%s retrievals=%d",
        plan.decision,
        len(plan.retrievals),
    )

    return {"plan": plan}


def retrieve_data(state: State) -> dict:
    """
    Execute all retrieval requests in the classifier plan.

    The graph stays simple because one node handles the retrieval loop.
    """

    plan = state["plan"]
    results = []

    for request in plan.retrievals:

        if request.source == "student_erp":

            if not request.student_id or not request.password:
                results.append(
                    {
                        "source": "student_erp",
                        "query": request.search_query or "",
                        "context": (
                            "Private ERP data could not be retrieved because "
                            "both student ID and ERP password are required."
                        ),
                    }
                )
                continue

            data = student_data(
                student_id=request.student_id,
                password=request.password,
            )

            if data is None:
                results.append(
                    {
                        "source": "student_erp",
                        "query": request.search_query or "",
                        "context": (
                            "The ERP retrieval failed. No verified student "
                            "ERP data was returned."
                        ),
                    }
                )
                continue

            data_text = (
                json.dumps(data, ensure_ascii=False, default=str)
                if isinstance(data, dict)
                else str(data)
            )

            results.append(
                {
                    "source": "student_erp",
                    "query": request.search_query or "",
                    "context": data_text,
                }
            )

        elif request.source == "college_database":

            query = request.search_query or state["input"]
            result = college_database_search(query)

            results.append(
                {
                    "source": "college_database",
                    "query": query,
                    "context": result.get("context", ""),
                }
            )

        elif request.source == "current_info":

            query = request.search_query or state["input"]
            result = current_info_search(query)

            results.append(
                {
                    "source": "current_info",
                    "query": query,
                    "context": result.get("context", ""),
                }
            )

    return {"retrieval_results": results}


def build_context(state: State) -> dict:
    """Build one clean context block before the final LLM call."""

    sections = []

    for result in state.get("retrieval_results", []):
        context = (result.get("context") or "").strip()

        if not context:
            continue

        sections.append(
            f"[SOURCE: {result.get('source', 'unknown')}]\n"
            f"[QUERY: {result.get('query', '')}]\n"
            f"{context}"
        )

    plan = state.get("plan")

    if plan and plan.denied_reason:
        sections.append(
            "[RETRIEVAL NOTE]\n"
            f"{plan.denied_reason}"
        )

    return {
        "context": "\\n\\n".join(sections).strip()
    }


def access_denied(state: State) -> dict:
    """Handle a request where the only needed retrieval is blocked."""

    plan = state["plan"]

    return {
        "output": (
            plan.denied_reason
            or (
                "I can retrieve private student ERP information only when "
                "you provide both your student ID and ERP password."
            )
        )
    }


def llm_call(state: State) -> dict:
    """Generate the final answer using the combined retrieval context."""

    context = state.get("context", "").strip()
    history = state.get("history", "").strip()

    prompt = f"""User query:
{state["input"]}
"""

    if history:
        prompt += f"""
Conversation history:
{history}
"""

    prompt += f"""
Retrieved context:
{context if context else "No retrieval was required."}
"""

    result = answer_model.invoke(
        [
            SystemMessage(content=SYSTEM_PROMPT),
            HumanMessage(content=prompt),
        ]
    )

    return {
        "output": getattr(result, "content", str(result))
    }


# ============================================================
# Routing
# ============================================================

def route_after_classifier(state: State) -> str:
    decision = state["plan"].decision

    if decision == "retrieval_not_required":
        return "llm_call"

    if decision == "access_denied":
        return "access_denied"

    return "retrieve_data"


# ============================================================
# Build graph
# ============================================================

graph = StateGraph(State)

graph.add_node("classifier", classify_request)
graph.add_node("retrieve_data", retrieve_data)
graph.add_node("build_context", build_context)
graph.add_node("access_denied", access_denied)
graph.add_node("llm_call", llm_call)

graph.add_edge(START, "classifier")

graph.add_conditional_edges(
    "classifier",
    route_after_classifier,
    {
        "retrieve_data": "retrieve_data",
        "access_denied": "access_denied",
        "llm_call": "llm_call",
    },
)

graph.add_edge("retrieve_data", "build_context")
graph.add_edge("build_context", "llm_call")

graph.add_edge("access_denied", END)
graph.add_edge("llm_call", END)

chat = graph.compile()

# Use for debugging to visualize the graph structure
# with open("graph.png", "wb") as f:
#     f.write(chat.get_graph().draw_mermaid_png())

# ============================================================
# Agent runner
# ============================================================

def run_agent(message: str, history: str = "") -> dict:
    config: RunnableConfig = {
        "configurable": {
            "thread_id": "1"
        }
    }

    state = chat.invoke(
        {
            "input": message,
            "history": history,
            "retrieval_results": [],
            "context": "",
            "output": "",
        },
        config,
    )

    context_text = state.get("context", "") or ""

    return {
        "reply": state.get("output", ""),
        "context_used": {
            "query": message,
            "context": context_text,
            "context_len": len(context_text) / 4 if context_text else 0,
        },
        "history": history,
    }


if __name__ == "__main__":
    example_message = (
        "What is my attendance and who is the CSE HOD? "
        "what are the current events happening this week?"
    )

    print(run_agent(example_message)["reply"])
